//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gemini.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _goto {
            get {
                object obj = ResourceManager.GetObject("_goto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap batch {
            get {
                object obj = ResourceManager.GetObject("batch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap changelog {
            get {
                object obj = ResourceManager.GetObject("changelog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap charmap {
            get {
                object obj = ResourceManager.GetObject("charmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closeTab {
            get {
                object obj = ResourceManager.GetObject("closeTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closeTabClick {
            get {
                object obj = ResourceManager.GetObject("closeTabClick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closeTabHover {
            get {
                object obj = ResourceManager.GetObject("closeTabHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comment {
            get {
                object obj = ResourceManager.GetObject("comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap computer {
            get {
                object obj = ResourceManager.GetObject("computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap debug {
            get {
                object obj = ResourceManager.GetObject("debug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap emptyspace {
            get {
                object obj = ResourceManager.GetObject("emptyspace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expand {
            get {
                object obj = ResourceManager.GetObject("expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_export {
            get {
                object obj = ResourceManager.GetObject("file_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_exports {
            get {
                object obj = ResourceManager.GetObject("file_exports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_flat {
            get {
                object obj = ResourceManager.GetObject("file_flat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_import {
            get {
                object obj = ResourceManager.GetObject("file_import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_imports {
            get {
                object obj = ResourceManager.GetObject("file_imports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_plus {
            get {
                object obj = ResourceManager.GetObject("file_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_update {
            get {
                object obj = ResourceManager.GetObject("file_update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fold {
            get {
                object obj = ResourceManager.GetObject("fold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_export {
            get {
                object obj = ResourceManager.GetObject("folder_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_import {
            get {
                object obj = ResourceManager.GetObject("folder_import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_plus {
            get {
                object obj = ResourceManager.GetObject("folder_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_recent {
            get {
                object obj = ResourceManager.GetObject("folder_recent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gemini {
            get {
                object obj = ResourceManager.GetObject("gemini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gemini_big {
            get {
                object obj = ResourceManager.GetObject("gemini_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap highlight {
            get {
                object obj = ResourceManager.GetObject("highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap highlightColor {
            get {
                object obj = ResourceManager.GetObject("highlightColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap highlightFinds {
            get {
                object obj = ResourceManager.GetObject("highlightFinds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap increaser {
            get {
                object obj = ResourceManager.GetObject("increaser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap indent {
            get {
                object obj = ResourceManager.GetObject("indent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap outline {
            get {
                object obj = ResourceManager.GetObject("outline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap recent {
            get {
                object obj = ResourceManager.GetObject("recent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reduce {
            get {
                object obj = ResourceManager.GetObject("reduce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap replace {
            get {
                object obj = ResourceManager.GetObject("replace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Bitmap Cache Color Font Game_Actor Game_Actors Game_BattleAction Game_Battler Game_Character Game_CommonEvent Game_Enemy Game_Event Game_Interpreter Game_Map Game_Message Game_Party Game_Picture Game_Player Game_Screen Game_SelfSwitches Game_Switches Game_System Game_Temp Game_Troop Game_Unit Game_Variables Game_Vehicle Graphics Input NKF Plane RGSSError RPG Rect Scene_Base Scene_Battle Scene_Debug Scene_End Scene_Equip Scene_File Scene_Gameover Scene_Item Scene_Map Scene_Menu Scene_Name Scene_Shop Sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RMVX_Constants {
            get {
                return ResourceManager.GetString("RMVX_Constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio\BGM Audio\BGS Audio\ME Audio\SE Data Fonts Graphics\Animations Graphics\Battlers Graphics\Characters Graphics\Faces Graphics\Parallaxes Graphics\Pictures Graphics\System.
        /// </summary>
        internal static string RMVX_Directories {
            get {
                return ResourceManager.GetString("RMVX_Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTEST RGSS_SCRIPTS TEST data_actors data_animations data_areas data_armors data_classes data_common_events data_enemies data_items data_skills data_states data_system data_troops data_weapons game_actors game_map game_message game_party game_player game_self_switches game_switches game_system game_temp game_troop game_variables scene.
        /// </summary>
        internal static string RMVX_Globals {
            get {
                return ResourceManager.GetString("RMVX_Globals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rmvx_icon {
            get {
                object obj = ResourceManager.GetObject("rmvx_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rmvx_script {
            get {
                object obj = ResourceManager.GetObject("rmvx_script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio BattleManager Bitmap Cache Color DataManager Font Game_Action Game_ActionResult Game_Actor Game_Actors Game_BaseItem Game_Battler Game_BattlerBase Game_Character Game_CharacterBase Game_CommonEvent Game_Enemy Game_Event Game_Follower Game_Followers Game_Interpreter Game_Map Game_Message Game_Party Game_Picture Game_Pictures Game_Player Game_Screen Game_SelfSwitches Game_Switches Game_System Game_Temp Game_Timer Game_Troop Game_Unit Game_Variables Game_Vehicle Graphics Input Plane RGSSError RGSSReset R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RMVXAce_Constants {
            get {
                return ResourceManager.GetString("RMVXAce_Constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio\BGM Audio\BGS Audio\ME Audio\SE Data Fonts Graphics\Animations Graphics\Battlebacks1 Graphics\Battlebacks2 Graphics\Battlers Graphics\Characters Graphics\Faces Graphics\Parallaxes Graphics\Pictures Graphics\System Graphics\Tilesets Graphics\Titles1 Graphics\Titles2 Movies System.
        /// </summary>
        internal static string RMVXAce_Directories {
            get {
                return ResourceManager.GetString("RMVXAce_Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTEST RGSS_SCRIPTS TEST data_actors data_animations data_armors data_classes data_common_events data_enemies data_items data_mapinfos data_skills data_states data_system data_tilesets data_troops data_weapons game_actors game_map game_message game_party game_player game_self_switches game_switches game_system game_temp game_timer game_troop game_variables.
        /// </summary>
        internal static string RMVXAce_Globals {
            get {
                return ResourceManager.GetString("RMVXAce_Globals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rmvxace_icon {
            get {
                object obj = ResourceManager.GetObject("rmvxace_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rmvxace_script {
            get {
                object obj = ResourceManager.GetObject("rmvxace_script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow_Actor Arrow_Base Arrow_Enemy Audio Bitmap Color Font Game_Actor Game_Actors Game_BattleAction Game_Battler Game_Character Game_CommonEvent Game_Enemy Game_Event Game_Map Game_Party Game_Picture Game_Player Game_Screen Game_SelfSwitches Game_Switches Game_System Game_Temp Game_Troop Game_Variables Graphics Hangup Input Interpreter Plane Rect RGSSError RPG Scene_Battle Scene_Debug Scene_End Scene_Equip Scene_File Scene_Gameover Scene_Item Scene_Load Scene_Map Scene_Menu Scene_Name Scene_Save Scene_Shop  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RMXP_Constants {
            get {
                return ResourceManager.GetString("RMXP_Constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio\BGM Audio\BGS Audio\ME Audio\SE Data Graphics\Animations Graphics\Autotiles Graphics\Battlebacks Graphics\Battlers Graphics\Characters Graphics\Fogs Graphics\Gameovers Graphics\Icons Graphics\Panoramas Graphics\Pictures Graphics\Tilesets Graphics\Titles Graphics\Transitions Graphics\Windowskins.
        /// </summary>
        internal static string RMXP_Directories {
            get {
                return ResourceManager.GetString("RMXP_Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTEST DEBUG RGSS_SCRIPTS data_actors data_animations data_armors data_classes data_common_events data_enemies data_items data_skills data_states data_system data_tilesets data_troops data_weapons game_actors game_map game_party game_player game_screen game_self_switches game_switches game_system game_temp game_troop game_variables scene.
        /// </summary>
        internal static string RMXP_Globals {
            get {
                return ResourceManager.GetString("RMXP_Globals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rmxp_icon {
            get {
                object obj = ResourceManager.GetObject("rmxp_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rmxp_script {
            get {
                object obj = ResourceManager.GetObject("rmxp_script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ruby {
            get {
                object obj = ResourceManager.GetObject("ruby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN END __ENCODING__ __END__ __FILE__ __LINE__ alias and begin break case class def defined? do else elsif end ensure false for if in module next nil not or redo rescue retry return self super then true undef unless until when while yield.
        /// </summary>
        internal static string Ruby_Keywords {
            get {
                return ResourceManager.GetString("Ruby_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARGF ARGV ArgumentError Array Bignum Binding Class Comparable Continuation Data Dir ENV EOFError Enumerable Errno Exception FALSE FalseClass File FileTest Fixnum Float FloatDomainError GC Hash IO IOError IndexError Integer Interrupt Kernel LoadError LocalJumpError Marshal MatchData MatchingData Math Method Module NIL NameError NilClass NoMemoryError NoMethodError NotImplementedError Numeric Object ObjectSpace PLATFORM Precision Proc Process RELEASE_DATE RUBY_PLATFORM RUBY_RELEASE_DATE RUBY_VERSION Range Ran [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ruby181_Constants {
            get {
                return ResourceManager.GetString("Ruby181_Constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; &lt;= &lt;=&gt; == === =~ &gt; &gt;= Array Float Integer String __id__ __send__ ` abort ancestors at_exit autoload autoload? binding block_given? callcc caller catch chomp chomp! chop chop! class class_eval class_variables clone const_defined? const_get const_missing const_set constants display dup eql? equal? eval exec exit exit! extend fail fork format freeze frozen? getc gets global_variables gsub gsub! hash id include? included_modules inspect instance_eval instance_method instance_methods instance_of? instance_vari [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ruby181_KernelFunctions {
            get {
                return ResourceManager.GetString("Ruby181_KernelFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARGF ARGV ArgumentError Array BasicObject Bignum Binding Class Comparable Complex DL Data Dir ENV EOFError Encoding EncodingError Enumerable Enumerator Errno Exception FALSE FalseClass Fiber FiberError File FileTest Fixnum Float FloatDomainError GC Hash IO IOError IndexError Integer Interrupt Kernel KeyError LoadError LocalJumpError Marshal MatchData Math Method Module Mutex NIL NameError NilClass NoMemoryError NoMethodError NotImplementedError Numeric Object ObjectSpace Proc Process RUBY_COPYRIGHT RUBY_DES [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ruby192_Constants {
            get {
                return ResourceManager.GetString("Ruby192_Constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! != !~ &lt; &lt;= &lt;=&gt; == === =~ &gt; &gt;= Array Complex Float Integer Rational String __callee__ __id__ __method__ __send__ ` abort ancestors at_exit autoload autoload? binding block_given? caller catch class class_eval class_exec class_variable_defined? class_variable_get class_variable_set class_variables clone const_defined? const_get const_missing const_set constants define_singleton_method display dup enum_for eql? equal? eval exec exit exit! extend fail fork format freeze frozen? gets global_variables hash incl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ruby192_KernelFunctions {
            get {
                return ResourceManager.GetString("Ruby192_KernelFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ruler {
            get {
                object obj = ResourceManager.GetObject("ruler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap run {
            get {
                object obj = ResourceManager.GetObject("run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap styles {
            get {
                object obj = ResourceManager.GetObject("styles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_complete {
            get {
                object obj = ResourceManager.GetObject("text_complete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_wrench {
            get {
                object obj = ResourceManager.GetObject("text_wrench", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wrench {
            get {
                object obj = ResourceManager.GetObject("wrench", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
